config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :users do
    resources :comments
    resources :posts do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
  validates :content, :presence => true
  after_initialize :set_defaults, unless: :persisted?

  def set_defaults
    self.vote = 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments, as: :commentable
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    
    @user.comments.build(comment_params).save
    @post.comments.build(comment_params).save

    if true
      redirect_to user_post_path(@user, @post)
    else
      @comment = Comment.new
      render :edit
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_path(@post.user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_path(@post.user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.user)
  end

private
  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render 'layouts/errors', :object => @comment %>

<%= form_for [@user, @post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form'%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for [@user, @post] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Code Discuss</h1>

<ul>
  <% @posts.each do |post| %>
  <% user = User.find(post.user_id) %>
  <p><%= link_to post.content, user_post_path(user, post) %> | <%= post.vote %> upvotes | By: <%= user.name %> </p>
  <hr>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.content %>

<% @post.comments.each do |comment| %>
  <%= comment.content %>
<% end %>

<%= render 'comments/form', :object => @comment %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user do |u| %>
  <%= u.label :name %>
  <%= u.text_field :name %>
  <%= u.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user_path(user) %> | <%= link_to "Edit", edit_user_path(user) %></li>
<% end %>
</ul>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<% if @user.posts.any? %>
  <h2>This user's posts:</h2>
  <ul>
    <% @user.posts.each do |p| %>
    <p>Post Content: <%= p.content %></p>
    <p>Current Vote: <%= p.vote %></p>
    <hr>
    <% end %>
  </ul>
<% else %>
  <p>This user has no posts</p>
<% end %>



  <p><%= link_to "Create Post", new_user_post_path(@user) %></p>
  <p><%= link_to "Delete User", user_path(@user), :data => {:confirm => "Are you sure?", :method => "delete"} %></p>